Add default support for scrolling with the mouse wheel.
martanne/dvtm pull request #104
Opened 2020-03-13 21:26 UTC by ccrusius

Also changes the scrollback() function so that the amount to scroll
can be configured as a fraction of the screen height.

This fixes #103.

2021-02-21 13:08 UTC, gwn commented
Hi, I'm a long time dvtm user. Just wanted to note that this patch seems to be working properly and I'm very happy with the feature, although I don't know about the implementation details. Thank you @ccrusius !

2021-03-04 07:15 UTC, KAction requested changes

2021-03-04 07:15 UTC, KAction commented on Makefile
> +config.h: config.def.h
This is bad. It will overwrite custom config.h

2021-03-04 07:15 UTC, KAction commented on dvtm.c
> +		vt_scroll(sel->term,  abs(div)/div);
This does not seem right. You compare div, which is essentially compile-time constant with buffer height.

2023-02-09 15:34 UTC, kugurerdem commented
I have also tried this patch and it seems to work very well. Thanks a lot @ccrusius !

2023-02-16 14:17 UTC, rpmohn commented
Shameless plug for a4 https://a4term.com which is a rewrite of dvtm and implements configurable scrolling with the mouse wheel by default. You can specify a number of lines to scroll (with an integer) or a percentage of a screen (with a decimal number). You can scroll whichever window the mouse is hovering over, not just the selected window. You can also use the mouse for additional configurable actions by clicking on a tag in the status bar, the layout symbol, and more. End of shameless plug.

2025-05-09 23:58 UTC, closed without merging